development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ninja_access_development
  pool: 5
  username: edvance
  password: s2cr2t
  socket: /var/run/mysqld/mysqld.sock

test: 
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ninja_access_test
  pool: 5
  username: edvance
  password: s2cr2t
  socket: /var/run/mysqld/mysqld.sock
