development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ninja_access_development
  pool: 5
  host: 127.0.0.1
  port: 3307
  username: root
  password: <root password>

test: 
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ninja_access_test
  pool: 5
  host: 127.0.0.1
  port: 3307
  username: root
  password: <root password>
