development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ninja_access_development
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test: 
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ninja_access_test
  pool: 5
  username:
  password:
  socket: /var/run/mysqld/mysqld.sock
